import {describe,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
import {makeRatingEmbed} from '../src/server/discord-format';
import {verifyLaunch} from '../scripts/verify-launch';
vi.mock('../src/server/db',()=>({query:vi.fn().mockResolvedValue({rows:[]})}));
const read=(path:string)=>readFileSync(path,'utf8');
function worker(keys:string[]){const handlers:Record<string,(event:any)=>void>={};const deleted:string[]=[];const added:string[][]=[];const opened:string[]=[];const self={location:{origin:'https://example.test'},clients:{claim:vi.fn()},skipWaiting:vi.fn(),addEventListener:(name:string,handler:any)=>handlers[name]=handler};runInNewContext(read('public/sw.js'),{self,URL,Response,fetch:vi.fn(),caches:{keys:async()=>keys,delete:async(key:string)=>{deleted.push(key);},open:async(key:string)=>{opened.push(key);return {addAll:async(paths:string[])=>added.push(paths)};}}});return{handlers,deleted,opened,added,self};}
describe('TasteBuds public brand and installed-app migration',()=>{
 it('preserves installed app identity while exposing the exact new display name',()=>{const manifest=JSON.parse(read('public/manifest.webmanifest'));expect(manifest).toMatchObject({id:'/',name:'TasteBuds',short_name:'TasteBuds',start_url:'/app',scope:'/'});});
 it('identifies the actual health route with TasteBuds while querying the existing schema',async()=>{const {GET}=await import('../src/app/api/health/route');const {query}=await import('../src/server/db');expect(await (await GET()).json()).toMatchObject({status:'ok',app:'TasteBuds'});expect(query).toHaveBeenCalledWith('SELECT id FROM everrate.groups LIMIT 1');});
 it('uses TasteBuds in outgoing Discord footers',()=>{expect(makeRatingEmbed({itemName:'Coffee',displayName:'Reviewer',score:8,note:null,itemId:'item'},'https://example.test').embeds[0].footer.text).toBe('Rated by Reviewer on TasteBuds');});
 it('installs the renamed public cache and removes both legacy brands without deleting unrelated caches',async()=>{const w=worker(['everrate-public-v1','scawwyrate-public-v1','tastebuds-public-v0','tastebuds-public-v1','tastebuds-public-v2','other-app-cache']);let promise:Promise<unknown>|undefined;w.handlers.install({waitUntil:(p:Promise<unknown>)=>promise=p});await promise;expect(w.opened).toEqual(['tastebuds-public-v2']);expect(w.added).toEqual([['/offline.html','/icon-192.png']]);w.handlers.activate({waitUntil:(p:Promise<unknown>)=>promise=p});await promise;expect(w.deleted.sort()).toEqual(['everrate-public-v1','scawwyrate-public-v1','tastebuds-public-v0','tastebuds-public-v1']);expect(w.self.clients.claim).toHaveBeenCalledOnce();});
 it('keeps authentication and private API/photo requests out of offline interception',()=>{const w=worker([]);for(const [pathname,mode]of [['/auth/callback','navigate'],['/api/photos/private','cors'],['/api/bootstrap','cors']]){const respondWith=vi.fn();w.handlers.fetch({request:{url:'https://example.test'+pathname,method:'GET',mode},respondWith});expect(respondWith).not.toHaveBeenCalled();}});
 it.each(['TasteBuds','EverRate'])('launch checks identify %s correctly',async(name)=>{const fetcher=async(input:any)=>{const path=new URL(input.toString()).pathname;if(path==='/')return new Response(`<title>${name}</title><a href="/auth/login">Sign in</a><link rel="manifest" href="/manifest.webmanifest">`,{headers:{'content-type':'text/html'}});if(path==='/api/health')return Response.json({status:'ok',app:name},{headers:{'cache-control':'no-store'}});if(path==='/manifest.webmanifest')return Response.json({...JSON.parse(read('public/manifest.webmanifest')),name});return Response.json({error:'Fixture not implemented'},{status:401});};const result=await verifyLaunch({baseUrl:'https://example.test',authOrigin:'https://auth.example.test'},fetcher as typeof fetch);for(const check of result.checks.filter(c=>['public-page','database-health','manifest'].includes(c.name)))expect(check.status).toBe(name==='TasteBuds'?'pass':'fail');});
});
