import {afterAll,afterEach,beforeAll,describe,expect,it,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {migrate} from '../scripts/migrate';
import {getPool} from '../src/server/db';
import * as service from '../src/server/service';
import {recognize} from '../src/server/recognition';
const url=process.env.TEST_DATABASE_URL;
if(url){const u=new URL(url);if(!['localhost','127.0.0.1','[::1]'].includes(u.hostname)||!u.pathname.endsWith('_test')||u.search)throw Error('Local disposable database required');}
describe.skipIf(!url)('self-only AI preferences and active reviewer counts',()=>{
 let admin:Pool,database:string,groupId:string,photoId:string,ratingId:string,itemId:string;
 const actor=randomUUID(),quiet=randomUUID(),deletedOnly=randomUUID(),former=randomUUID(),provider='900000000000000501';
 beforeAll(async()=>{admin=new Pool({connectionString:url});database='everrate_preferences_'+randomUUID().replaceAll('-','')+'_test';await admin.query(`CREATE DATABASE "${database}"`);const target=new URL(url!);target.pathname='/'+database;await migrate(target.toString());process.env.DATABASE_URL=target.toString();for(const id of [actor,quiet,deletedOnly,former])await service.ensureUser({id,displayName:'Synthetic reviewer',...(id===actor?{discordId:provider}:{})});const group=await service.createGroup(actor,{name:'Preference fixture'});groupId=group.id;for(const id of [quiet,deletedOnly,former])await service.joinGroup(id,{code:group.inviteCode!});photoId=(await getPool().query("INSERT INTO everrate.photos(group_id,owner_id,data,sha256,mime_type,width,height) VALUES($1,$2,$3,$4,'image/jpeg',1,1) RETURNING id",[groupId,actor,Buffer.from('synthetic-photo'),'a'.repeat(64)])).rows[0].id;const r=await service.createRating(actor,{groupId,name:'Tea',score:7.5,photoId});ratingId=r.id;itemId=r.itemId;await service.createRating(actor,{groupId,itemId,score:8,photoId});await getPool().query("INSERT INTO everrate.ratings(group_id,item_id,user_id,score,photo_id,deleted_at) VALUES($1,$2,$3,5,$4,now()),($1,$2,$5,6,$4,NULL)",[groupId,itemId,deletedOnly,photoId,former]);await service.removeMember(actor,groupId,former);});
 afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();});afterAll(async()=>{await getPool().end();await admin.query(`DROP DATABASE "${database}"`);await admin.end();});
 it('defaults existing and new people to disabled and refuses provider/cache/job access',async()=>{expect((await service.bootstrap(actor)).user.aiEnabled).toBe(false);const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(recognize(actor,photoId)).rejects.toMatchObject({status:403});expect(fetch).not.toHaveBeenCalled();expect((await getPool().query('SELECT count(*)::int n FROM everrate.recognition_jobs')).rows[0].n).toBe(0);});
 it('updates only the requesting canonical user with strict boolean input',async()=>{const before=(await getPool().query('SELECT to_jsonb(u) row FROM everrate.users u WHERE id=$1',[actor])).rows[0].row;expect(await service.updatePreferences(actor,{aiEnabled:true})).toMatchObject({id:actor,aiEnabled:true});const after=(await getPool().query('SELECT to_jsonb(u) row FROM everrate.users u WHERE id=$1',[actor])).rows[0].row;expect({...after,ai_enabled:before.ai_enabled}).toEqual(before);expect((await service.bootstrap(quiet)).user.aiEnabled).toBe(false);for(const input of [{},{aiEnabled:'true'},{aiEnabled:1},{aiEnabled:null},{aiEnabled:true,userId:quiet},{aiEnabled:true,nickname:'Not here'}])await expect(service.updatePreferences(actor,input)).rejects.toMatchObject({status:400});await expect(service.updatePreferences(randomUUID(),{aiEnabled:true})).rejects.toMatchObject({status:404});});
 it('preserves preference and nickname through concurrent provider refresh and nickname-only edits',async()=>{await service.updateNickname(actor,{nickname:'Tea pal'});await Promise.all([service.ensureUser({id:randomUUID(),discordId:provider,displayName:'New provider handle'}),service.updatePreferences(actor,{aiEnabled:false})]);expect((await service.bootstrap(actor)).user).toMatchObject({id:actor,aiEnabled:false,nickname:'Tea pal',displayName:'Tea pal'});await service.updatePreferences(actor,{aiEnabled:true});await service.updateNickname(actor,{nickname:'Evening tea'});expect((await service.bootstrap(actor)).user).toMatchObject({aiEnabled:true,nickname:'Evening tea'});await expect(service.updateNickname(actor,{nickname:'No mutation',aiEnabled:false})).rejects.toMatchObject({status:400});});
 it('rechecks opt-in after waiting for the recognition lock and avoids new jobs/provider calls',async()=>{await service.updatePreferences(actor,{aiEnabled:true});const held=await getPool().connect(),fetch=vi.fn();vi.stubGlobal('fetch',fetch);await held.query('BEGIN');await held.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`recognition:${actor}`]);const pending=recognize(actor,photoId).then(value=>({value,error:null as any}),error=>({value:null,error}));try{let blocked=false;for(let n=0;n<100;n++){blocked=(await getPool().query("SELECT count(*)::int n FROM pg_locks WHERE locktype='advisory' AND NOT granted AND database=(SELECT oid FROM pg_database WHERE datname=current_database())")).rows[0].n>0;if(blocked)break;await new Promise(resolve=>setTimeout(resolve,10));}expect(blocked).toBe(true);await service.updatePreferences(actor,{aiEnabled:false});await held.query('COMMIT');expect((await pending).error).toMatchObject({status:403});expect(fetch).not.toHaveBeenCalled();expect((await getPool().query('SELECT count(*)::int n FROM everrate.recognition_jobs')).rows[0].n).toBe(0);}finally{await held.query('ROLLBACK');held.release();}});
 it('does not return cached AI suggestions after the user opts out',async()=>{await getPool().query("INSERT INTO everrate.recognition_jobs(group_id,user_id,photo_id,photo_hash,model,prompt_version,status,result) SELECT group_id,$1,id,sha256,'gemini-3.1-flash-lite','everrate-2-photo-identity','completed',$3 FROM everrate.photos WHERE id=$2",[actor,photoId,{name:'Tea',brand:null,variant:null,type:'Tea',broadCategory:'drinks',confidence:.9}]);await service.updatePreferences(actor,{aiEnabled:false});const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(recognize(actor,photoId)).rejects.toMatchObject({status:403});expect(fetch).not.toHaveBeenCalled();expect((await getPool().query('SELECT count(*)::int n FROM everrate.recognition_jobs')).rows[0].n).toBe(1);});
 it('keeps photo ownership and group authorization when AI is enabled',async()=>{await service.updatePreferences(quiet,{aiEnabled:true});const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(recognize(quiet,photoId)).rejects.toMatchObject({status:403});await service.updatePreferences(former,{aiEnabled:true});await expect(recognize(former,photoId)).rejects.toMatchObject({status:404});expect(fetch).not.toHaveBeenCalled();});
 it('counts each active current reviewer once while retaining the full management roster',async()=>{const people=await service.listPeople(quiet,groupId);expect(people.map(p=>p.id)).toEqual([actor]);expect(people[0]).toMatchObject({ratingCount:2,itemCount:1});const group=await service.getGroup(quiet,groupId);expect(group.memberCount).toBe(1);expect(group.stats.activeMembers).toBe(1);expect(group.members.map(m=>m.id).sort()).toEqual([actor,quiet,deletedOnly].sort());expect((await service.bootstrap(quiet)).groups.find(g=>g.id===groupId)?.memberCount).toBe(1);expect((await service.getPersonRatings(quiet,groupId,deletedOnly)).ratings).toEqual([]);});
 it('keeps zero-review members authorized and groups visible when all current ratings are deleted',async()=>{await service.deleteRating(actor,ratingId);const remaining=(await service.getPersonRatings(actor,groupId,actor)).ratings[0];await service.deleteRating(actor,remaining.id);expect(await service.listPeople(quiet,groupId)).toEqual([]);const group=await service.getGroup(actor,groupId);expect(group).toMatchObject({memberCount:0,role:'owner',stats:{activeMembers:0}});expect(group.members).toHaveLength(3);expect((await service.bootstrap(quiet)).groups.map(g=>g.id)).toContain(groupId);expect(await service.rotateInvite(actor,groupId)).toHaveProperty('inviteCode');});
});
