'use client';
import {RatingStatus} from './rating-status';
import {BrandLabel} from './brand-label';
import {matchesBrowseCategory} from '../domain/browse-categories';
import {matchesItemSearch} from '../domain/item-search';
import {useEffect,useRef,useState} from 'react';
import {House,BookOpen,Activity,BarChart3,Settings,Plus,Search,LogOut,ArrowUpRight,Users,Star,Menu,NotebookPen} from 'lucide-react';
import type {Bootstrap,GroupDetail,Item,ItemDetail as Detail,FeedEntry,Rating} from '@/lib/contracts';
import {Avatar,BrandMark,Modal,Photo,Score,request,date} from './ui';
import {SelectMenu} from './select-menu';
import {RatingForm} from './rating-form';
import {ItemDetail} from './item-detail';
import {GroupSettings} from './group-settings';
import {CollectionHome} from './collection-home';
import {CategoryFilters} from './category-filters';
import {ItemCard} from './item-card';
import {GroupPodium} from './group-podium';
import {People} from './people';
import {AccountSettings,NicknameOnboarding} from './nickname';
type Tab='home'|'collection'|'feed'|'stats'|'settings'|'people'|'mine';
type GroupLoad={groupId:string;revision:number;status:'loading'|'ready'|'error';group:GroupDetail|null;items:Item[];feed:FeedEntry[]};
async function allItems(groupId:string){const result:Item[]=[];for(let offset=0;;offset+=200){const page=await request<Item[]>(`/api/groups/${groupId}/items?limit=200&offset=${offset}`);result.push(...page);if(page.length<200)return result;}}
export function AppClient(){
  const [boot,setBoot]=useState<Bootstrap|null>(null),[groupId,setGroupId]=useState(''),[groupLoad,setGroupLoad]=useState<GroupLoad|null>(null),[tab,setTab]=useState<Tab>('home');
  const [search,setSearch]=useState(''),[brand,setBrand]=useState(''),[type,setType]=useState<string|null>(''),[sort,setSort]=useState('recent'),[error,setError]=useState(''),[revision,setRevision]=useState(0),[groupsModal,setGroupsModal]=useState(false);
  const [rating,setRating]=useState<{item?:Item;editing?:Rating}|null>(null),[detail,setDetail]=useState<string|null>(null),[notice,setNotice]=useState('');
  const [personId,setPersonId]=useState<string|null>(null);
  const personalEdit=useRef<AbortController|null>(null);
  useEffect(()=>()=>personalEdit.current?.abort(),[groupId,tab,personId,revision,rating,detail,groupsModal]);
  const currentLoad=groupLoad?.groupId===groupId&&groupLoad.revision===revision?groupLoad:null;
  const group=currentLoad?.group||null,items=currentLoad?.items||[],feed=currentLoad?.feed||[];
  const loading=Boolean(groupId)&&(!currentLoad||currentLoad.status==='loading');
  const refresh=()=>setRevision(v=>v+1);
  const nicknameSaved=(user:Bootstrap['user'])=>{setBoot(previous=>previous?{...previous,user}:previous);setNotice('Your nickname has been updated.');refresh();};
  const preferencesSaved=(user:Bootstrap['user'])=>{setBoot(previous=>previous?{...previous,user}:previous);setNotice('Your photo preference has been updated.');refresh();};
  const openPerson=(id:string|null)=>{setPersonId(id);setDetail(null);setTab('people');};
  async function editPersonalReview(ratingId:string,itemId:string){
    personalEdit.current?.abort();const operation=new AbortController();personalEdit.current=operation;
    try{
      const item=await request<Detail>(`/api/items/${itemId}`,'GET',undefined,operation.signal),entry=item.ratings.find(r=>r.id===ratingId);
      if(operation.signal.aborted)return;
      if(!entry||entry.author.id!==boot?.user.id||item.groupId!==groupId)throw new Error('This review is no longer available to edit.');
      setDetail(null);setRating({editing:entry,item});
    }catch(e){if(!operation.signal.aborted)throw e;}
    finally{if(personalEdit.current===operation)personalEdit.current=null;}
  }
  const switchGroup=(id:string)=>{setGroupId(id);setSearch('');setType('');setBrand('');setDetail(null);setRating(null);setPersonId(null);};
  useEffect(()=>{let active=true;request<Bootstrap>('/api/bootstrap').then(v=>{if(!active)return;setBoot(v);setGroupId(previous=>v.groups.some(g=>g.id===previous)?previous:v.groups[0]?.id||'');}).catch(e=>{if(active){setError(e.message);}});return()=>{active=false;};},[revision]);
  useEffect(()=>{if(!groupId){setGroupLoad(null);return;}let active=true;const empty:GroupLoad={groupId,revision,status:'loading',group:null,items:[],feed:[]};setGroupLoad(empty);setError('');Promise.all([request<GroupDetail>(`/api/groups/${groupId}`),allItems(groupId),request<FeedEntry[]>(`/api/groups/${groupId}/feed?limit=100`)]).then(([g,i,f])=>{if(active)setGroupLoad({groupId,revision,status:'ready',group:g,items:i,feed:f});}).catch(e=>{if(active){setGroupLoad({...empty,status:'error'});setError(e.message);}});return()=>{active=false;};},[groupId,revision]);
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get('item');if(!id)return;let active=true;void request<Item>(`/api/items/${encodeURIComponent(id)}`).then(item=>{if(active){setGroupId(item.groupId);setDetail(item.id);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  const filtered=items.filter(i=>(!brand||i.brand===brand)&&matchesBrowseCategory(i.type,type)&&matchesItemSearch(i,search)).sort((a,b)=>sort==='score'?(b.average??-1)-(a.average??-1):sort==='name'?a.name.localeCompare(b.name):sort==='most-rated'?b.tastingCount-a.tastingCount:new Date(b.lastRatedAt||0).getTime()-new Date(a.lastRatedAt||0).getTime());
  const brands=[...new Set(items.flatMap(i=>i.brand?[i.brand]:[]))].sort();
  const nav=[{id:'home' as Tab,label:'Home',icon:House},{id:'collection' as Tab,label:'Collection',icon:BookOpen},{id:'feed' as Tab,label:'Group feed',icon:Activity},{id:'stats' as Tab,label:'Our taste',icon:BarChart3},{id:'mine' as Tab,label:'My reviews',icon:NotebookPen},{id:'settings' as Tab,label:'Settings',icon:Settings}];
  if(!boot)return <main className="loading-screen"><span className="wordmark"><BrandMark/></span>{error?<><p className="error">{error}</p><button className="button primary" onClick={refresh}>Try again</button></>:<p>Opening your collection…</p>}</main>;
  if(boot.user.nickname===null)return <NicknameOnboarding user={boot.user} saved={nicknameSaved}/>;
  return <div className="app-shell"><aside className="sidebar"><a className="wordmark" href="/app"><BrandMark/></a><div className="group-picker"><span>Your group</span><SelectMenu label="Your group" value={groupId} onChange={switchGroup} options={boot.groups.map(g=>({value:g.id,label:g.name}))} placeholder="No groups yet"/></div><nav aria-label="Main navigation">{nav.map(n=><button key={n.id} className={tab===n.id?'active':''} onClick={()=>setTab(n.id)}><n.icon size={20}/>{n.label}</button>)}</nav><button className="button secondary" onClick={()=>setGroupsModal(true)}><Users size={16}/> Create or join a group</button><div className="sidebar-bottom"><Avatar name={boot.user.displayName} url={boot.user.avatarUrl}/><span>{boot.user.displayName}</span><button className="icon-button" aria-label="Sign out" onClick={()=>void request('/auth/logout','POST',{}).then(()=>window.location.href='/').catch(e=>setError(e.message))}><LogOut size={18}/></button></div></aside>
  <main className="workspace" data-view={tab}><header className="mobile-header"><a className="wordmark" href="/app"><BrandMark/></a><SelectMenu label="Your group" value={groupId} onChange={switchGroup} options={boot.groups.map(g=>({value:g.id,label:g.name}))} placeholder="No groups yet"/><button className="icon-button" aria-label="Create or join a group" onClick={()=>setGroupsModal(true)}><Plus/></button></header>
    {error&&<div className="error" role="alert">{error}<button onClick={refresh}>Try again</button></div>}{notice&&<div className="success" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notification">×</button></div>}
    {tab==='settings'&&<AccountSettings user={boot.user} saved={nicknameSaved} preferencesSaved={preferencesSaved}/>}
    {!groupId&&tab==='settings'?null:!groupId?<section className="onboarding"><div className="onboarding-symbol"><Users size={44}/></div><h1>Good taste starts<br/>with good company.</h1><p>Create a private group or join your friends with an invite code.</p><button className="button primary" onClick={()=>setGroupsModal(true)}>Find your people <ArrowUpRight size={18}/></button></section>:<>
    {tab!=='settings'&&<header className="page-header" key={tab}><div><div className="group-label">{group?.name||boot.groups.find(g=>g.id===groupId)?.name||'Your group'} <button className="text-button" onClick={()=>openPerson(null)} aria-label="Browse people in this group"><Users size={14}/> {group?.memberCount||0} people</button></div><h1>{tab==='home'?'What are we trying next?':tab==='collection'?'The things we’ve tried.':tab==='feed'?'Fresh opinions.':tab==='mine'?'My reviews.':tab==='people'?'Your people. Their taste.':'A taste of the group.'}</h1><p>{tab==='home'?'Your group’s collection, ready to explore.':tab==='collection'?'Every find, every flavour, every opinion.':tab==='feed'?'See what your people have been trying.':tab==='mine'?'Your tastings, your opinions. Edit or remove a review whenever you need.':tab==='people'?'Explore each person’s ratings, from their first try to their latest.':'Different people. A collection of shared favourites.'}</p></div><button className="button primary" disabled={!group||loading} onClick={()=>setRating({})}><Plus size={19}/> Add a rating</button></header>}
    {loading?<div className="loading-content" role="status">Gathering your group’s ratings…</div>:!group?null:tab==='home'?<CollectionHome key={groupId} items={items} browse={value=>{setType(value);setBrand('');setSearch('');setTab('collection');}} open={setDetail} add={()=>setRating({})}/>:tab==='collection'?<><div className="collection-tools"><label className="search"><Search size={19}/><input aria-label="Search collection" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find an item, brand or restaurant…"/></label><SelectMenu label="Filter by brand or restaurant" value={brand} onChange={setBrand} searchable options={[{value:"",label:"All brands / restaurants"},...brands.map(v=>({value:v,label:v}))]}/><SelectMenu label="Sort collection" value={sort} onChange={setSort} options={[{value:"recent",label:"Recently tried"},{value:"score",label:"Highest rated"},{value:"name",label:"Name A–Z"},{value:"most-rated",label:"Most tried"}]}/></div><CategoryFilters key={groupId} items={items} value={type} onChange={setType}/>
    {filtered.length===0?<div className="empty-state"><BookOpen size={36}/><h2>{items.length?'Nothing matches just yet.':'Your next discovery belongs here.'}</h2><p>{items.length?'Try another name or clear your filters.':'Snap a photo and add your first rating to start the collection.'}</p><button className="button secondary" onClick={()=>items.length?(setSearch(''),setBrand(''),setType('')):setRating({})}>{items.length?'Clear filters':'Add the first rating'}</button></div>:<div className="item-grid">{filtered.map(i=><ItemCard key={i.id} item={i} open={setDetail}/>)}</div>}</>:tab==='feed'?<div className="feed-list">{feed.length===0?<div className="empty-state"><Activity size={36}/><h2>The conversation starts with a rating.</h2><p>Try something and tell the group what you think.</p></div>:feed.map(r=><article className="feed-card" key={r.id}><Avatar name={r.author.displayName} url={r.author.avatarUrl}/><div className="feed-content"><p><button className="text-button" onClick={()=>openPerson(r.author.id)}><strong>{r.author.displayName}</strong></button> {r.isRereview?'rereviewed':'tried'} <button className="text-button" onClick={()=>setDetail(r.itemId)}><strong>{r.itemName}</strong></button></p><BrandLabel brand={r.brand}/><small>{date(r.tastedAt)}</small><RatingStatus rating={r}/>{r.note&&<p className="note">{r.note}</p>}</div><Score value={r.score}/>{r.photoId&&<Photo id={r.photoId} name={r.itemName}/>}</article>)}</div>:(tab==='people'||tab==='mine')?<People key={`${groupId}-${tab}-${revision}`} groupId={groupId} personId={tab==='mine'?boot.user.id:personId} select={openPerson} open={setDetail} viewerId={boot.user.id} edit={editPersonalReview} changed={refresh}/>:tab==='stats'?<><div className="stat-strip"><div><strong>{group?.stats.itemCount||0}</strong><span>things tried</span></div><div><strong>{group?.stats.tastingCount||0}</strong><span>individual tastings</span></div><div><strong>{group?.stats.activeMembers||0}</strong><span>people sharing their taste</span></div></div><GroupPodium key={groupId} items={items} open={setDetail} browse={()=>{setType('');setBrand('');setSearch('');setTab('collection');}}/><div className="stats-columns"><section><h2>Coming back for more</h2><p className="muted">The items with the most tastings.</p><div className="repeat-list">{[...items].sort((a,b)=>b.tastingCount-a.tastingCount).slice(0,10).map(i=><button className="ranking" key={i.id} onClick={()=>setDetail(i.id)}><Photo id={i.photoId} name={i.name}/><div className="ranking-copy"><strong>{i.name}</strong><BrandLabel brand={i.brand}/>{!i.brand&&i.type&&<small>{i.type}</small>}</div><span className="tasting-count">{i.tastingCount}<small>{i.tastingCount===1?'tasting':'tastings'}</small></span></button>)}</div></section></div></>:group&&<GroupSettings key={`${group.id}-${revision}`} group={group} user={boot.user} changed={refresh}/>}</>}
  </main>{group&&tab!=='settings'&&<button className="button primary mobile-rate-cta" disabled={loading} onClick={()=>setRating({})}><Plus size={22}/><span>Add a rating</span></button>}<nav className="bottom-nav" aria-label="Mobile navigation">{nav.map(n=><button key={n.id} className={tab===n.id?'active':''} onClick={()=>setTab(n.id)}><n.icon size={20}/><span>{n.label}</span></button>)}</nav>
  {groupsModal&&<GroupsModal close={()=>setGroupsModal(false)} saved={id=>{switchGroup(id);setGroupsModal(false);refresh();}}/>}
  {rating&&groupId&&<RatingForm aiEnabled={boot.user.aiEnabled} groupId={rating.item?.groupId||groupId} item={rating.item} editing={rating.editing} close={()=>setRating(null)} saved={()=>{setRating(null);setNotice('Rating saved. It’s part of the collection.');refresh();}}/>}
  {detail&&!rating&&<ItemDetail key={`${detail}-${revision}`} id={detail} user={boot.user} owner={group?.role==='owner'} person={openPerson} close={()=>setDetail(null)} rate={item=>{setGroupId(item.groupId);setRating({item});}} edit={(editing,item)=>{setGroupId(item.groupId);setRating({editing,item});}} changed={refresh}/>}
  </div>;
}
function GroupsModal({close,saved}:{close:()=>void;saved:(id:string)=>void}){
  const [mode,setMode]=useState<'create'|'join'>('create'),[value,setValue]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  return <Modal title="Find your people" close={close}><div className="segmented"><button className={mode==='create'?'selected':''} onClick={()=>{setMode('create');setValue('');}}>Create a group</button><button className={mode==='join'?'selected':''} onClick={()=>{setMode('join');setValue('');}}>Join a group</button></div><form className="rating-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const g=await request<{id:string}>(mode==='create'?'/api/groups':'/api/groups/join','POST',mode==='create'?{name:value}:{code:value});saved(g.id);}catch(e){setError(e instanceof Error?e.message:'Could not continue.');setBusy(false);}}}><p className="muted">{mode==='create'?'A private space for friends, family, or your next tasting club.':'Ask a group owner for their invite code.'}</p><label>{mode==='create'?'Group name':'Invite code'}<input required autoFocus maxLength={120} value={value} onChange={e=>setValue(e.target.value)} placeholder={mode==='create'?'The usual suspects':'Paste your invite code'}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?'One moment…':mode==='create'?'Create group':'Join group'}</button></form></Modal>;
}
