'use client';
import {useState} from 'react';
import type {GroupDetail,User} from '@/lib/contracts';
import {request} from './ui';
import {InstallApp} from './install-app';
export function GroupSettings({group,user,changed}:{group:GroupDetail;user:User;changed:()=>void}){
  const [name,setName]=useState(group.name),[url,setUrl]=useState(''),[enabled,setEnabled]=useState(group.discordConnected),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[removing,setRemoving]=useState<string|null>(null);
  const owner=group.role==='owner';
  async function run(fn:()=>Promise<unknown>,message:string){setBusy(true);setError('');setSuccess('');try{await fn();setSuccess(message);changed();}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);setRemoving(null);}}
  return <section className="settings"><header className="section-title"><h1>Group settings</h1><p>Make this space yours.</p></header>{error&&<p className="error" role="alert">{error}</p>}{success&&<p className="success" role="status">{success}</p>}
    <div className="settings-section"><h2>TasteBuds on your device</h2><p>Open your collection from your home screen or desktop.</p><InstallApp/><button className="text-button" onClick={()=>void request('/auth/logout','POST',{}).then(()=>window.location.href='/').catch(e=>setError(e.message))}>Sign out of TasteBuds</button></div>
    {owner&&<><form className="settings-section" onSubmit={e=>{e.preventDefault();void run(()=>request(`/api/groups/${group.id}`,'PATCH',{name}),'Group name updated.');}}><h2>The group</h2><label>Group name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><button className="button primary" disabled={busy}>Save name</button></form><div className="settings-section"><h2>Invite your people</h2><p>Anyone with this code can join your private group. Share it with people you trust.</p><div className="invite-code">{group.inviteCode}</div><div className="button-row"><button className="button secondary" onClick={()=>void run(()=>navigator.clipboard.writeText(group.inviteCode||''),'Invite code copied.')}>Copy code</button><button className="text-button" disabled={busy} onClick={()=>void run(()=>request(`/api/groups/${group.id}/invite`,'POST',{}),'New invite code created. The old code no longer works.')}>Create a new code</button></div></div>
    <form className="settings-section" onSubmit={e=>{e.preventDefault();void run(async()=>{await request(`/api/groups/${group.id}/discord`,'POST',{enabled,url:url||undefined});setUrl('');},'Discord settings saved.');}}><h2>Bring the conversation to Discord</h2><p>Post new ratings to a channel you choose. Your existing ratings won’t be posted.</p><label className="checkbox"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Share new ratings in Discord</label><label>Discord channel webhook URL<input type="password" autoComplete="off" value={url} onChange={e=>setUrl(e.target.value)} placeholder={group.discordConnected?'Connected — enter a URL to replace':'https://discord.com/api/webhooks/…'}/></label><small className="muted">In Discord, open Channel settings → Integrations → Webhooks. Copy its URL here. The connection is stored securely.</small><button className="button primary" disabled={busy}>Save Discord connection</button></form></>}
    <div className="settings-section"><h2>Your people <span className="count">{group.members.length}</span></h2>{group.members.map(m=><div className="member" key={m.id}><div className="avatar">{m.displayName.slice(0,1)}</div><div><strong>{m.displayName}{m.id===user.id?' (you)':''}</strong><small>{m.role==='owner'?'Group owner':'Member'}</small></div>{owner&&m.id!==user.id&&<div className="member-actions"><button className="text-button" disabled={busy} onClick={()=>setRemoving(`owner:${m.id}`)}>Make owner</button><button className="text-button danger" disabled={busy} onClick={()=>setRemoving(m.id)}>Remove</button></div>}</div>)}
    {removing&&<div className="inline-confirm"><p>{removing.startsWith('owner:')?'Transfer ownership? You will become a regular member.':'Remove this member’s access to the group? Their existing ratings stay.'}</p><button disabled={busy} onClick={()=>void run(()=>removing.startsWith('owner:')?request(`/api/groups/${group.id}`,'PATCH',{ownerId:removing.slice(6)}):request(`/api/groups/${group.id}/members/${removing}`,'DELETE'),'Membership updated.')}>Confirm</button><button onClick={()=>setRemoving(null)}>Cancel</button></div>}
    {!owner&&<button className="button secondary danger" disabled={busy} onClick={()=>void run(()=>request(`/api/groups/${group.id}`,'PATCH',{leave:true}),'You left the group.')}>Leave group</button>}</div>
  </section>;
}
