'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Bookmark,HeartHandshake} from 'lucide-react';
import type {Item,TasteInsights as Insights} from '@/lib/contracts';
import {brandSummary,categoryChoices,filterPersonalItems,type PersonalFilter} from '../domain/personal-discovery';
import {matchesBrowseCategory} from '../domain/browse-categories';
import {ItemCard} from './item-card';
import {SelectMenu} from './select-menu';
import {Avatar,request} from './ui';
export function PersonalFilters({items,value,onChange}:{items:Item[];value:PersonalFilter;onChange:(value:PersonalFilter)=>void}){
 return <div className="personal-filters" role="group" aria-label="Your collection filters">{([{value:'all',label:'All items',count:items.length},{value:'untried',label:'Untried by me',count:items.filter(i=>i.myScore==null).length},{value:'saved',label:'Want to try',count:items.filter(i=>i.saved).length}] as const).map(option=><button type="button" key={option.value} aria-pressed={value===option.value} className={value===option.value?'selected':''} onClick={()=>onChange(option.value)}>{option.value==='saved'&&<Bookmark size={15}/>}<span>{option.label}</span><small>{option.count}</small></button>)}</div>;
}
export function BrandPage({name,items,open,back}:{name:string;items:Item[];open:(id:string)=>void;back:()=>void}){
 const [category,setCategory]=useState(''),[filter,setFilter]=useState<PersonalFilter>('all'),[sort,setSort]=useState('group');
 const summary=brandSummary(items,name),categories=categoryChoices(summary.items.map(i=>i.type));
 const categoryItems=summary.items.filter(i=>matchesBrowseCategory(i.type,category));
 const visible=filterPersonalItems(categoryItems,filter).sort((a,b)=>sort==='mine'?(b.myScore??-1)-(a.myScore??-1)||a.name.localeCompare(b.name):(b.average??-1)-(a.average??-1)||b.raterCount-a.raterCount||a.name.localeCompare(b.name));
 return <section className="brand-page"><button className="text-button back" onClick={back}><ArrowLeft size={16}/> Back to collection</button><header className="brand-hero"><div><span className="eyebrow">Explore the brand</span><h1>{name}</h1><p>{summary.total} items · {summary.tried} tried by you · {summary.saved} saved</p></div>{summary.favourite&&<button className="personal-favourite" onClick={()=>open(summary.favourite!.id)}><span>Your favourite</span><strong>{summary.favourite.name}</strong><b>{summary.favourite.myScore?.toFixed(1)}<small>/10</small></b></button>}</header><div className="brand-tools"><SelectMenu label="Brand category" value={category} onChange={setCategory} searchable options={[{value:'',label:'All categories'},...categories.map(c=>({value:c,label:c}))]}/><SelectMenu label="Brand ranking" value={sort} onChange={setSort} options={[{value:'group',label:'Highest group score'},{value:'mine',label:'My highest score'}]}/></div><PersonalFilters items={categoryItems} value={filter} onChange={setFilter}/><p className="hint brand-ranking-note">Each person’s latest score counts once. Reviewer bubbles show who has tried each item.</p>{visible.length?<div className="item-grid">{visible.map(item=><ItemCard key={item.id} item={item} open={open}/>)}</div>:<div className="empty-state"><h2>No items here yet.</h2><p>Try another category or personal filter.</p><button className="button secondary" onClick={()=>{setFilter('all');setCategory('');}}>Show all {name} items</button></div>}</section>;
}
export function TasteInsights({groupId,open,person}:{groupId:string;open:(id:string)=>void;person:(id:string)=>void}){
 const [insights,setInsights]=useState<Insights|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();setInsights(null);setError('');void request<Insights>(`/api/groups/${groupId}/taste`,'GET',undefined,controller.signal).then(value=>{if(!controller.signal.aborted)setInsights(value);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[groupId,retry]);
 return <section className="taste-insights"><header><HeartHandshake size={26}/><div><h2>On the same wavelength</h2><p>Find your taste twins—and the things you disagree on.</p></div></header>{error?<p className="error" role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>Try again</button></p>:!insights?<p role="status">Comparing your latest scores…</p>:<><div className="taste-matches">{insights.matches.length?insights.matches.map(match=><article className="taste-match" key={match.person.id}><button className="taste-person" onClick={()=>person(match.person.id)}><Avatar name={match.person.displayName} url={match.person.avatarUrl}/><strong>{match.person.displayName}</strong></button><p><b>{match.meanDifference.toFixed(1)}</b><span>/10 average score difference</span></p><small>{match.sharedCount} shared items · {match.similarCount} scored within 1 point</small>{match.disagreements.length>0&&<details><summary>Your biggest disagreements</summary>{match.disagreements.map(d=><button className="taste-disagreement" key={d.itemId} onClick={()=>open(d.itemId)}><strong>{d.itemName}</strong><span>You {d.myScore.toFixed(1)} · {match.person.displayName} {d.theirScore.toFixed(1)}</span></button>)}</details>}</article>):<p className="taste-empty">Rate at least three of the same items as a friend to see how your tastes compare. We’ll use only your latest scores.</p>}</div><div className="divisive-items"><h3>Love it or leave it</h3><p className="hint">The widest score spreads, with at least three different people rating.</p>{insights.divisive.length?insights.divisive.map(item=><button key={item.itemId} onClick={()=>open(item.itemId)}><span><strong>{item.itemName}</strong><small>{item.brand}{item.brand?' · ':''}{item.raterCount} people</small></span><b>{item.lowScore.toFixed(1)}–{item.highScore.toFixed(1)}<small>/10</small></b></button>):<p className="taste-empty">The group’s most divisive discoveries will appear here as more people rate.</p>}</div></>}</section>;
}
